#warning:make sure you are only entering TAB chatacters, not 
#mixtures of TAB and spaces. Always remember to indent.


CFLAGS=-Wall -g

clean:
	rm -f ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13
